theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

title: Kidlo-th
description: Chase everything you love in life.

logo: /assets/img/fav.jpg
#show_downloads: truegoogle_analytics:
google_analytics:

repository: fangchd/fangchd.github.io
github:
  owner_url: https://github.com/kidlo-th

email_one: uingfour@gmail.com
